from typing import Any, Protocol


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password: str, hashed_password: str) -> bool: ...


class TokenService(Protocol):
    def create_access_token(self, subject: str) -> str: ...

    def decode_access_token(self, token: str) -> dict[str, Any]: ...

    def generate_refresh_token(self) -> str: ...

    def hash_refresh_token(self, raw_token: str) -> str: ...
