from fastapi import APIRouter

from app.api.v1.routers import (
    accounts,
    admin,
    advisor,
    alerts,
    analytics,
    api_keys,
    appointment,
    audit,
    auth,
    blueprint,
    catalog,
    clients,
    cnpj,
    companies,
    connectors,
    dashboard,
    employees,
    financial,
    goals,
    health,
    income_statement,
    insights,
    invitations,
    notifications,
    oauth_callback,
    plans,
    public_api,
    recurring,
    reports,
    subscription,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(companies.router)
api_router.include_router(blueprint.router)
api_router.include_router(financial.router)
api_router.include_router(clients.router)
api_router.include_router(catalog.router)
api_router.include_router(employees.router)
api_router.include_router(dashboard.router)
api_router.include_router(insights.router)
api_router.include_router(audit.router)
api_router.include_router(notifications.router)
api_router.include_router(advisor.router)
api_router.include_router(appointment.router)
api_router.include_router(connectors.router)
api_router.include_router(oauth_callback.router)
api_router.include_router(cnpj.router)
api_router.include_router(invitations.router)
api_router.include_router(plans.router)
api_router.include_router(subscription.router)
api_router.include_router(admin.router)
api_router.include_router(analytics.router)
api_router.include_router(alerts.router)
api_router.include_router(goals.router)
api_router.include_router(recurring.router)
api_router.include_router(accounts.router)
api_router.include_router(income_statement.router)
api_router.include_router(reports.router)
api_router.include_router(api_keys.router)
api_router.include_router(public_api.router)
